#!/usr/bin/env python3
"""
How to test from commandline:
    echo -e "col0${TAB}col1${TAB}col2${TAB}col3\ncol0_${TAB}col1_${TAB}col2_${TAB}col3_\ncol0__${TAB}col1__${TAB}col2__${TAB}col3__" | cut_by_column_name -fcol0
"""

import sys

if len(sys.argv) > 3 or len(sys.argv) == 1:
    exit(1)
if not sys.argv[1].startswith("-f"):
    exit(1)

try:
    col_to_cut = sys.argv[1].split("-f")[1].split(",")
except:
    exit(1)

def filter_file(our_input):
    header = {}
    for il, line in enumerate(our_input):
        if il == 0:
            header = { colname: icol for icol, colname in enumerate(line.rstrip().split('\t')) }

        line = line.rstrip().split('\t')
        try:
            assert(len(line) == len(header.keys()))
        except:
            print("[Error] Wrong number of columns in line {}".format(il))
            exit(1)

        columns = []
        for colname in col_to_cut:
            columns.append(line[header[colname]])
        print("\t".join(columns))

if len(sys.argv) == 2:
    our_input = sys.stdin
    filter_file(our_input)
else:
    our_input=open(sys.argv[-1])
    filter_file(our_input)
    close(our_input)
