#!/bin/bash -x

echo "How to add new mappings?"
echo "Use command xmodmap -pme to see all keys mapped to meta keys (control, alt, modifiers)."
echo "Next: remove needed key from current meta key."
echo "Next: add needed key to needed meta key."

# Reset all.
setxkbmap -option

# Here example how to map F7:
# xmodmap -e 'keycode 74 = Tab' #F7
# xmodmap -e 'keycode 134 = Next' #F7

# Set keyboard type.
echo "Keyboard type (options: mac, erg, acer)"
read keyboard_type
[ "$keyboard_type" == "" ] && echo "Set default to mac." && keyboard_type=mac


# Common ---
# Caps lock as enter.
setxkbmap -option caps:none 
xmodmap -e 'keycode 66 = Return'    #caps lock as enter
# ---

if [ "$keyboard_type" == "mac" ]; then
    xmodmap -e 'remove mod4 = Super_R'  
    xmodmap -e 'add shift = Super_R'
    # -- 
    xmodmap -e 'remove mod4 = Super_L'
    xmodmap -e 'add control = Super_L'
    # -- 
    xmodmap -e 'remove control = Control_L'
    xmodmap -e 'add mod4 = Control_L'
fi

if [ "$keyboard_type" == "erg" ]; then
    xmodmap -e 'remove control = Control_L' 
    xmodmap -e 'add mod1 = Control_L' 

    xmodmap -e 'remove mod1 = Alt_L' 
    xmodmap -e 'add control = Alt_L' 

    xmodmap -e 'remove mod4 = Super_L' 
    xmodmap -e 'add mod1 = Super_L'

    #right alt and right super
    # xmodmap -e 'remove mod5 = ISO_Level3_Shift' 
    # xmodmap -e 'add shift = ISO_Level3_Shift'

    #right alt and right super
    xmodmap -e 'remove mod1 = Alt_R' 
    xmodmap -e 'add shift = Alt_R'
fi
