#!/bin/bash -x

echo "How to add new mappings?"
echo "Use command xmodmap -pme to see all keys mapped to meta keys (control, alt, modifiers)."
echo "Next: remove needed key from current meta key."
echo "Next: add needed key to needed meta key."

# Set keyboard type.
echo "Keyboard type (options: mac, erg, acer, ergi)"
keyboard_type="$1"
[ "$keyboard_type" == "" ] && echo "Set default to mac." && keyboard_type=ergi

if [ "$keyboard_type" == "mac" ]; then
    echo "Mac keyboard template loading.."
    setxkbmap -option
    setxkbmap -option caps:none 
    xmodmap -e 'keycode 66 = Return'    #caps lock as enter
    # ---

    xmodmap -e 'remove mod4 = Super_R'  
    xmodmap -e 'add shift = Super_R'
    # -- 
    xmodmap -e 'remove mod4 = Super_L'
    xmodmap -e 'add control = Super_L'
    # -- 
    xmodmap -e 'remove control = Control_L'
    xmodmap -e 'add mod4 = Control_L'
fi

if [ "$keyboard_type" == "erg" ]; then
    echo "Ergonomic home template loading.."
    setxkbmap -option
    setxkbmap -option caps:none 
    xmodmap -e 'keycode 66 = Return'    #caps lock as enter
    # ---

    xmodmap -e 'remove control = Control_L' 
    xmodmap -e 'add mod4 = Control_L' 

    xmodmap -e 'remove mod1 = Alt_L' 
    xmodmap -e 'add control = Alt_L' 

    xmodmap -e 'remove mod4 = Super_L' 
    xmodmap -e 'add mod1 = Super_L'

    #right alt and right super
    # case home
    xmodmap -e 'remove mod1 = Alt_R' 
    xmodmap -e 'add shift = Alt_R'
fi

if [ "$keyboard_type" == "ergi" ]; then
    echo "Ergonomic intel template loading.."
    setxkbmap -option
    setxkbmap -option caps:none 
    xmodmap -e 'keycode 66 = Return'    #caps lock as enter
    # ---

    xmodmap -e 'remove control = Control_L' 
    xmodmap -e 'add mod4 = Control_L' 

    xmodmap -e 'remove mod1 = Alt_L' 
    xmodmap -e 'add control = Alt_L' 

    xmodmap -e 'remove mod4 = Super_L' 
    xmodmap -e 'add mod1 = Super_L'

    xmodmap -e 'remove mod5 = ISO_Level3_Shift' 
    xmodmap -e 'add shift = ISO_Level3_Shift'
fi
