#!/bin/bash -e

# caps lock as enter
setxkbmap -option caps:none 
xmodmap -e 'keycode 66 = KP_Enter NoSymbol KP_Enter' 

#right alt and right super
xmodmap -e 'remove mod5 = ISO_Level3_Shift' 
xmodmap -e 'add shift = ISO_Level3_Shift'
xmodmap -e 'remove mod5 = ISO_Level3_Shift'  
xmodmap -e 'add shift = ISO_Level3_Shift' 
