export ZSH=/home/felidadae/.oh-my-zsh

ZSH_THEME="felidadae"
HYPHEN_INSENSITIVE="true"
# ENABLE_CORRECTION="true"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search)

source $ZSH/oh-my-zsh.sh

#felidadae
export __MY_SHELL__="zsh"
source ~/Programming/_General/bashProfile/AllFatherOfAllSons.sh

#zsh autosuggest colors
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
ZSH_HIGHLIGHT_STYLES[default]='fg=yellow,bold' #base1
ZSH_HIGHLIGHT_STYLES[alias]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[function]='fg=white'
ZSH_HIGHLIGHT_STYLES[command]='fg=blue'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=green,bold' #base01
ZSH_HIGHLIGHT_STYLES[path]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=blue,bold' #base0
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=blue,bold' #base0
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=red,bold' #orange


# show which vim mode we are in
precmd() {
  RPROMPT=""
}
zle-keymap-select() {
  RPROMPT=""
  [[ $KEYMAP = vicmd ]] && RPROMPT="(COMMAND MODE)"
  () { return $__prompt_status }
  zle reset-prompt
}
zle-line-init() {
  typeset -g __prompt_status="$?"
}
zle -N zle-keymap-select
zle -N zle-line-init


# bindkeys 
# @Documentation
#	Use showkeys -a or cat to see which escape sequences needed t
KEY_LEFT='^[[D'
KEY_BRACKET_LEFT='^?^?{'
#	Set vim mode
bindkey -v # to set vi mode
export KEYTIMEOUT=10 # i dont really understand whats the fuck going on here
#	Bindings:
bindkey -M viins 'jk' vi-cmd-mode
bindkey '^[r' history-incremental-search-backward
bindkey -M viins "op[$KEY_BRACKET_LEFT" forward-char #complete gray history
bindkey -M vicmd v edit-command-line
bindkey -M viins -s ']\' '|'
bindkey -M viins -s ',wc' '| wc -l'
bindkey -M viins -s 'tre' "trans pl:en ''$KEY_LEFT"
bindkey -M viins -s 'ytr' "trans -p en:es ''$KEY_LEFT"
bindkey -M vicmd -s ,su '0isudo jk$i '
bindkey -M viins -s '.gm' "git commit -m ''$KEY_LEFT"
bindkey -M viins -s '.pe' "perl -pe 's///g' *$KEY_LEFT"

# function sep_ { for i in {1..50}; do printf '*'; done; echo; }
# function tr_ { sep_; trans pl:en "$1"; sep_; trans pl:es "$1"; sep_; }
# bindkey -M viins -s 'tre' "tr_ \"\"$KEY_LEFT" #translate
# bindkey -M viins -s 'tre' "trans pl: \"\"$KEY_LEFT" #translate
# bindkey -M viins -s 'trer' "trans en:es \"\"$KEY_LEFT" #translate
