export ZSH=~/.oh-my-zsh
case $(uname -a) in
  *Microsoft*) unsetopt BG_NICE ;;
esac
#set history size
export HISTSIZE=20000
#save history after logout
export SAVEHIST=20000
#history file
export HISTFILE=~/.zsh_history
#append into history file
setopt INC_APPEND_HISTORY
#save only one command if 2 common are same and consistent
setopt HIST_IGNORE_DUPS
#add timestamp for each entry
setopt EXTENDED_HISTORY

ZSH_THEME=""
HYPHEN_INSENSITIVE="true"
# ENABLE_CORRECTION="true"

plugins=(git zsh-history-substring-search clipboard conda)
source $ZSH/oh-my-zsh.sh

# show which vim mode we are in
bindkey -v
precmd() {
  RPROMPT=""
}
zle-keymap-select() {
  RPROMPT=""
  [[ $KEYMAP = vicmd ]] && RPROMPT="(COMMAND MODE)"
  () { return $__prompt_status }
  zle reset-prompt
}
zle-line-init() {
  typeset -g __prompt_status="$?"
}
zle -N zle-keymap-select
zle -N zle-line-init

export DISABLE_AUTO_TITLE=true
[ ! -d ~/.zshnip_ ] && git clone https://github.com/facetframer/zshnip ~/.zshnip_
source ~/.zshnip_/zshnip.zsh

#felidadae
export __MY_SHELL__="zsh"
source ~/Programming/_General/shellProfile/AllFatherOfAllSons.sh
source ~/Programming/_General/felidadaeTools/spanishLearner/main.zsh

if [ -e /usr/local/bin/virtualenvwrapper.sh ]; then
	function virtualenv_prompt_info(){
	  [[ -n ${VIRTUAL_ENV} ]] || return
	  echo "${ZSH_THEME_VIRTUALENV_PREFIX:=[}${VIRTUAL_ENV:t}${ZSH_THEME_VIRTUALENV_SUFFIX:=]}"
	}
	export WORKON_HOME=~/Envs
	export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
	export VIRTUAL_ENV_DISABLE_PROMPT=1
	mkdir -p $WORKON_HOME
	source /usr/local/bin/virtualenvwrapper.sh
	VIRTUAL_ENV="system-wide"
fi

if [ -d ~/miniconda3 ]; then
	PATH="$PATH:/home/felidadae/miniconda3/bin"
fi

if [ ! -e $_sources/z/z.sh ]; then
	git clone https://github.com/rupa/z.git $_sources/z
fi
source $_sources/z/z.sh

if [ ! -d ~/.fzf ]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
