"----------------------------------------------------------------------------------
" @Plugins
source ~/.vim/vimrc_splitted/plugins.vim
"----------------------------------------------------------------------------------

let g:ycm_server_use_vim_stdout = 1
let g:ycm_server_log_level = 'debug'

"----------------------------------------------------------------------------------
" @must-be-on-top (for some reason this settings has to be on the top of the
" file)
" @powerline @tabber
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
set tabline=%!tabber#TabLine()
"----------------------------------------------------------------------------------


"----------------------------------------------------------------------------------
" @encoding @indent @general
source ~/.vim/vimrc_splitted/general_settings.vim "general vim settings
"----------------------------------------------------------------------------------


"----------------------------------------------------------------------------------
" @plugin-settings
source ~/.vim/vimrc_splitted/plugins_settings.vim
"----------------------------------------------------------------------------------


"----------------------------------------------------------------------------------
" @mappings (note: contains also mappings for plugins)
source ~/.vim/vimrc_splitted/mappings.vim "also contains mappings for plugins
"----------------------------------------------------------------------------------


"----------------------------------------------------------------------------------
" @additional
source ~/.vim/vimrc_splitted/folding.vim "foldtext foldmethod per filetype
source ~/.vim/vimrc_splitted/helper_functions.vim "custom vim functions
source ~/.vim/vimrc_splitted/tabs_settings.vim
"----------------------------------------------------------------------------------


"----------------------------------------------------------------------------------
" @must-be-on-end (for some reasons this commands has to be on the end of the
" whole settings file)

:hi nontext ctermfg=bg
:hi folded term=none cterm=none ctermfg=none ctermbg=none
:hi Normal ctermbg=none
:hi foldcolumn ctermbg=none

" after a re-source, fix syntax matching issues (concealing brackets):
if exists('g:loaded_webdevicons')
    call webdevicons#refresh()
endif
"----------------------------------------------------------------------------------
