Program(source = "embedding1.cc", target = "embedding1",
        LIBS = ['boost_python', 'python2.7'],
        LIBPATH = ['/usr/lib/python2.7'],
        CPPPATH = ['/usr/include/python2.7'])

Program(source = "embedding2.cc", target = "embedding2",
        LIBS = ['boost_python', 'python2.7'],
        LIBPATH = ['/usr/lib/python2.7'],
        CPPPATH = ['/usr/include/python2.7'])


