all:
    hosts: 
        dupa:
        dupa2:
    vars:
        janek_2: "{{kasia}}"
        kasia: "{{janek}}"
        slowniczek:
          klucz1: wartosc1
          klucz2: wartosc2
          klucz3: wartosc3
          klucz4: wartosc4
    children:
        other_group:
            hosts:
                127.0.0.1:
            vars:
                zmienna: 17
                janek_9: "{{janek_8}}"
                janek_8: "{{janek_2}}"
                ansible_connection: local
