<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tasklist</string>
	</array>
	<key>name</key>
	<string>Task List</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ssraw</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.other.special-method</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>^\s*(\[.?\])\s*(\@)([a-zA-Z\.\,]*)?((-&gt;)?(\{.*\}))?</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>^\s*\#.*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>\d\d\d\d\.\d\d\.\d\d</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.taskList</string>
	<key>uuid</key>
	<string>13b5718f-ce34-488e-9f4a-d3855f96a457</string>
</dict>
</plist>
